apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: miles-applicationset
  annotations:
      argocd.argoproj.io/sync-options: Validate=false
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          # git generator 'child' #1
          - git:
              #repoURL: https://github.com/bobby.kim-nsuslab/multi-cluster-argo-demo.git
              repoURL: https://github.com/mileslee-nsuslab/miles-helm-repo.git
              revision: main
              directories:
              - path: devops/*
               
          - list:
              # v0.2.0+ form - does not require cluster/URL keys
              # (but they are still supported).
              elements:
              # - cluster: dev
              #   url: https://3389448CB7BEED329CD8156430E49395.gr7.ap-northeast-2.eks.amazonaws.com
              #   brand: wsop
                # template:
                #   spec:
                #     syncPolicy:
                #       automated: {}
                #syncOptions: ["ApplyOutOfSyncOnly=true","PrunePropagationPolicy=background"]
              - cluster: develop
                url: https://kubernetes.default.svc
                brand: global
                team: devops
              - cluster: test
                url:  https://17BBBC38D86559D9B3B3E360DFF30CD8.sk1.us-east-1.eks.amazonaws.com
                brand: global
                team: devops
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}-{{brand}}'
      labels:
        team: '{{team}}'
        brand: '{{brand}}'
        env: '{{cluster}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/mileslee-nsuslab/miles-helm-repo.git
          targetRevision: main
          helm:
            valueFiles:
              - $value/values.yaml
        - repoURL: https://github.com/mileslee-nsuslab/miles-helm-repo.git
          targetRevision: main
          ref: value
        - repoURL: https://github.com/mileslee-nsuslab/miles-helm-repo.git
          targetRevision: main
          path: sealed-secrets/{{path[1]}}/{{cluster}}/{{path[2]}}
      destination:
        server: '{{url}}' 
        namespace: 'default'
      syncPolicy:
        automated:
          prune: true
        syncOptions: 
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=background
          - CreateNamespace=true
