{{- $fullName := include "chart-template.fullname" . -}}
{{- range $i, $v := .Values.persistentVolumeClaims -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name | default (printf "%s-%d" $fullName $i) }} 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
  volumeMode: Filesystem
{{- end }}